module.exports = {
  env: {
    NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY: process.env.NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY,
    NEXT_PUBLIC_PROGRAM_PRICE: process.env.NEXT_PUBLIC_PROGRAM_PRICE,
    NEXT_PUBLIC_SUBACCOUNT_CODE: process.env.NEXT_PUBLIC_SUBACCOUNT_CODE,
  },
  publicRuntimeConfig: {
    NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY: process.env.NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY,
    NEXT_PUBLIC_PROGRAM_PRICE: process.env.NEXT_PUBLIC_PROGRAM_PRICE,
    NEXT_PUBLIC_SUBACCOUNT_CODE: process.env.NEXT_PUBLIC_SUBACCOUNT_CODE,
  },
}